server:
  shutdown: graceful
  lifecycle:
    timeout-per-shutdown-phase: 30s
  port: 8080
  servlet:
    session:
      cookie:
        name: IDPSIM_SESSION
        path: /
        http-only: true
        secure: true
        same-site: none

logging:
  level:
    root: INFO